"""Add balance table

Revision ID: 5d3c9a41e054
Revises: 3fe229022c28
Create Date: 2022-09-25 10:44:54.584811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3c9a41e054'
down_revision = '3fe229022c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###