"""Inital migration

Revision ID: 64cf9c28fdde
Revises: 7bda2488d606
Create Date: 2022-09-25 12:23:54.455052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cf9c28fdde'
down_revision = '7bda2488d606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###