"""Inital migration

Revision ID: 320073c6ecce
Revises: f0c88c9b0681
Create Date: 2022-09-25 12:14:08.541878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320073c6ecce'
down_revision = 'f0c88c9b0681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###