"""Inital migration

Revision ID: 621e1a8fea61
Revises: 1a03f003dd03
Create Date: 2022-09-25 12:16:14.342380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621e1a8fea61'
down_revision = '1a03f003dd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###