"""Add balance table

Revision ID: 3fe229022c28
Revises: 118a78a6aaae
Create Date: 2022-09-25 10:41:23.098343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe229022c28'
down_revision = '118a78a6aaae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###