"""Add balance table

Revision ID: 118a78a6aaae
Revises: 45753a7c0643
Create Date: 2022-09-25 10:39:12.240757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118a78a6aaae'
down_revision = '45753a7c0643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###