"""Inital migration

Revision ID: 1a03f003dd03
Revises: 320073c6ecce
Create Date: 2022-09-25 12:15:23.899675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a03f003dd03'
down_revision = '320073c6ecce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###